version: 2
updates:
  # Poetry (Python) in the docs directory
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"

  # pnpm (JavaScript/Node.js) in the root directory
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
